name: Feature Merged

on:
  push:
    branches:
      - develop

jobs:     
  deploy-staging:
    name: Deploy Staging
    environment:
      name: staging
      url: https://staging.example.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [backend, web, helper-web, service]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run:
          sleep 30s && echo "${{ matrix.packages }} deploy done"
  