name: Feature Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [backend, web, helper-web, service]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run:
          sleep 30s && echo "${{ matrix.packages }} build done"
  
  test:
    name: Test Unit
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [backend, web, helper-web, service]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run:
          sleep 30s && echo "${{ matrix.packages }} test done"

  deploy-develop:
    name: Deploy Develop
    needs: test
    environment:
      name: develop
      url: https://develop.example.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [backend, web, helper-web, service]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run:
          sleep 30s && echo "${{ matrix.packages }} deploy done"
  
        
            
    