name: Release Merged

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    strategy:
      matrix:
        packages: [backend, web, helper-web, service]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run:
          sleep 30s && echo "${{ matrix.packages }} deploy done"

  sync-branch:
      name: Sync Branch
      needs: deploy-production
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Merge development -> staging
          uses: devmasx/merge-branch@master
          with:
            type: now
            from_branch: main
            target_branch: develop
            github_token: ${{ secrets.GITHUB_TOKEN }}